# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [1]:
import numpy as np

# Criar um array de elementos de 10 a 100
array1 = np.arange(10, 101)

# Inverter o array
array1_invertido = array1[::-1]

# Criar um array 3x3 com valores de 0 a 8
array2 = np.arange(9).reshape(3, 3)

# Criar um array identidade de 6x6
array_identidade = np.eye(6)

# Criar um array com valores aleatórios com o formato 3x3x3
array_aleatorio = np.random.random((3, 3, 3))

# Criar dois arrays, com valores aleatórios, A e B
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Verificar se os arrays A e B são iguais
sao_iguais = np.array_equal(A, B)

# Imprimir os resultados
print("Array de 10 a 100:", array1)
print("\nArray invertido:", array1_invertido)
print("\nArray 3x3 com valores de 0 a 8:\n", array2)
print("\nArray identidade 6x6:\n", array_identidade)
print("\nArray aleatório 3x3x3:\n", array_aleatorio)
print("\nArray A:\n", A)
print("\nArray B:\n", B)
print("\nOs arrays A e B são iguais?", sao_iguais)

Array de 10 a 100: [ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]

Array invertido: [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]

Array 3x3 com valores de 0 a 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Array identidade 6x6:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Array a

**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [2]:
import numpy as np

# Criar um array de 100 elementos aleatórios entre 1 e 1000
dolares = np.random.randint(1, 1001, 100)

# Taxa de conversão de dólares para euros
taxa_conversao = 0.874413

# Fazer a conversão dos preços em dólares para euros
euros = dolares * taxa_conversao

# Arredondar o array de euros para 2 casas decimais
euros_arredondado = np.round(euros, 2)

# Mostrar os resultados
print("Array de dólares:\n", dolares)
print("\nArray de euros:\n", euros_arredondado)

Array de dólares:
 [580 101 561 962 867 137 100 946 476 238 302 142 880 765 802 840 157 419
 865 598 495 224 888 568 358 813 712 495 297 371 874 490 541 110  41 119
 364 205 518 127 662  97 834 987 981  57 206 504 710  10 848 880  77 385
  91 908 576 790  18 627 957 397 511 490 593 312 674 705 459 670 378 355
 807 519 396 980 644 755 139 754  41 107 471 486 188 816 110 822 380 445
 598 727 922 431 526 737 320 161 650 625]

Array de euros:
 [507.16  88.32 490.55 841.19 758.12 119.79  87.44 827.19 416.22 208.11
 264.07 124.17 769.48 668.93 701.28 734.51 137.28 366.38 756.37 522.9
 432.83 195.87 776.48 496.67 313.04 710.9  622.58 432.83 259.7  324.41
 764.24 428.46 473.06  96.19  35.85 104.06 318.29 179.25 452.95 111.05
 578.86  84.82 729.26 863.05 857.8   49.84 180.13 440.7  620.83   8.74
 741.5  769.48  67.33 336.65  79.57 793.97 503.66 690.79  15.74 548.26
 836.81 347.14 446.83 428.46 518.53 272.82 589.35 616.46 401.36 585.86
 330.53 310.42 705.65 453.82 346.27 856.92 563.12 660.18 121

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [ ]:
# Importar pandas e usar um alias
import pandas as pd

# Carregar o dataframe de títulos e mostrar os 5 primeiros registros
titulos = pd.read_csv('05_05_imdb_títulos.csv')
print("Primeiros 5 registros do dataframe de títulos:")
print(titulos.head())

# Carregar o dataframe de elenco e mostrar os 5 primeiros registros
elenco = pd.read_csv('05_05_imdb_elenco.csv')
print("\nPrimeiros 5 registros do dataframe de elenco:")
print(elenco.head())

# Mostrar o número de registros do dataframe de títulos
print("\nNúmero de registros do dataframe de títulos:", len(titulos))

# Mostrar o número de registros do dataframe de elenco
print("Número de registros do dataframe de elenco:", len(elenco))

# Mostrar as 5 títulos mais antigas
print("\nOs 5 títulos mais antigos:")
print(titulos.sort_values('ano').head())

# Mostrar os filmes que no título contêm a palavra “Drácula” e contar quantos são
dracula_filmes = titulos[titulos['título'].str.contains('Drácula', case=False)]
print("\nNúmero de filmes com a palavra 'Drácula' no título:", len(dracula_filmes))
print(dracula_filmes)

# Mostrar os 10 títulos mais comuns
print("\nOs 10 títulos mais comuns:")
print(titulos['título'].value_counts().head(10))

# Mostrar o primeiro filme chamado “Romeo and Juliet”
romeo_and_juliet_first = titulos[titulos['título'] == 'Romeo and Juliet'].sort_values('ano').iloc[0]
print("\nO primeiro filme chamado 'Romeo and Juliet':")
print(romeo_and_juliet_first)

# Listar todos os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente
exorcist_filmes = titulos[titulos['título'].str.contains('Exorcist', case=False)].sort_values('ano')
print("\nFilmes que contenham a palavra 'Exorcist', ordenados do mais antigo ao mais recente:")
print(exorcist_filmes)

# Mostrar quantos filmes foram feitos no ano 1950
filmes_1950 = len(titulos[titulos['ano'] == 1950])
print("\nNúmero de filmes feitos no ano 1950:", filmes_1950)

# Mostrar quantos filmes foram feitos de 1950 a 1959 (inclusive)
filmes_1950_1959 = len(titulos[(titulos['ano'] >= 1950) & (titulos['ano'] <= 1959)])
print("Número de filmes feitos de 1950 a 1959:", filmes_1950_1959)

# Mostrar todos os papéis da trilogia “The Godfather”, agrupando pelo papel e fornecendo a informação da quantidade de vezes esse papel apareceu
godfather_roles = elenco[elenco['filme'].isin(['The Godfather', 'The Godfather: Part II', 'The Godfather: Part III'])]
godfather_roles_count = godfather_roles['papel'].value_counts()
print("\nPapéis na trilogia 'The Godfather', agrupados pelo papel e contagem de aparições:")
print(godfather_roles_count)

# Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958
dracula_1958_cast = elenco[(elenco['filme'] == 'Drácula') & (elenco['ano'] == 1958)].sort_values('n')
print("\nElenco completo do filme 'Drácula' de 1958, ordenado pela classificação 'n':")
print(dracula_1958_cast)

# Mostrar quantos papéis teve “Bruce Wayne” como protagonista
bruce_wayne_roles = elenco[(elenco['personagem'] == 'Bruce Wayne') & (elenco['n'] == 1)]
print("\nNúmero de papéis em que 'Bruce Wayne' aparece como protagonista:", len(bruce_wayne_roles))

# Mostrar quantos papéis fez “Robert de Niro” na sua carreira
robert_de_niro_roles = len(elenco[elenco['nome'] == 'Robert De Niro'])
print("\nNúmero de papéis feitos por 'Robert De Niro' na sua carreira:", robert_de_niro_roles)

# Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado por ano de forma descendente
charlton_heston_roles_60s = elenco[(elenco['nome'] == 'Charlton Heston') & (elenco['n'] == 1) & (elenco['ano'] >= 1960) & (elenco['ano'] <= 1969)].sort_values('ano', ascending=False)
print("\nPapéis como protagonista de 'Charlton Heston' na década de 60, ordenados por ano de forma descendente:")
print(charlton_heston_roles_60s)

# Mostrar quantos papéis para atores teve na década 50’s
atores_roles_50s = len(elenco[(elenco['n'].notna()) & (elenco['ano'] >= 1950) & (elenco['ano'] <= 1959)])
print("\nNúmero de papéis para atores na década de 50:", atores_roles_50s)

# Mostrar quantos papéis para atrizes teve na década 50’s
atrizes_roles_50s = len(elenco[(elenco['n'].notna()) & (elenco['ano'] >= 1950) & (elenco['ano'] <= 1959) & (elenco['tipo'] == 'actress')])
print("Número de papéis para atrizes na década de 50:", atrizes_roles_50s)